baseURL = 'https://emergent-rva.com/'
languageCode = 'en-us'
title = 'emergent-rva.com'
theme = 'hugo-noir'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1

[params]
    name = "emergent-rva"
    description = "Personal website, digital resume, and blog."
    profile_image = "/images/profile.jpg"
    github = "https://github.com/jay13jay"
    email = "josh@emergent-rva.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"
